server.port=8080

spring.datasource.url=jdbc:mysql://roundhouse.proxy.rlwy.net:50251/railway
spring.datasource.username=root
spring.datasource.password=FXmDXfiZCCiPxhAepgDPgFkSeGArfWX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
